
host: 144.34.149.150

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${host}:3306/mybatis_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.bbz.core.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
